# Generated by Django 2.2.11 on 2021-01-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("better_reads", "0002_shelfbook"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="rate",
            field=models.CharField(
                blank=True,
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5")],
                max_length=1,
            ),
        ),
    ]
