# Generated by Django 2.2.11 on 2021-01-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("better_reads", "0003_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelfbook",
            name="status",
            field=models.CharField(
                choices=[("wish", "wish"), ("reading", "reading"), ("read", "read")],
                default="wish",
                max_length=10,
            ),
        ),
    ]
