# Generated by Django 2.2.11 on 2021-01-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("better_reads", "0004_choiceFeild"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review", name="content", field=models.TextField(blank=True),
        ),
    ]
