# Generated by Django 2.2.11 on 2021-01-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("better_reads", "0005_reviewBlankContent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(null=True, upload_to="book_covers/"),
        ),
    ]
